# Generated by Django 4.2.4 on 2024-03-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.CharField(max_length=100)),
                ('biografia', models.CharField(max_length=3500)),
                ('foto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Productoras',
            fields=[
                ('id_productora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('anno_estreno', models.IntegerField()),
                ('duracion_minutos', models.IntegerField()),
                ('titulo', models.CharField(max_length=3500)),
                ('poster', models.CharField(max_length=255)),
                ('bg_imagen', models.CharField(max_length=255)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.directores')),
                ('productora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productoras')),
            ],
        ),
    ]
